In [2]:
import pandas as pd
import numpy as np

In [3]:
from numpy import log,dot,exp,shape
from sklearn.metrics import confusion_matrix

In [4]:
df=pd.read_csv('suv_data.csv')

In [5]:
print(df.head())

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0


In [6]:
x = df.iloc[:, [2, 3]].values
y = df.iloc[:, 4].values

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.10, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print (x_train[0:10,:])


[[-1.05714987  0.53420426]
 [ 0.2798728  -0.51764734]
 [-1.05714987  0.41733186]
 [-0.29313691 -1.45262654]
 [ 0.47087604  1.23543867]
 [-1.05714987 -0.34233874]
 [-0.10213368  0.30045946]
 [ 1.33039061  0.59264046]
 [-1.15265148 -1.16044554]
 [ 1.04388575  0.47576806]]


In [9]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)
LogisticRegression (random_state=0)
y_pred = classifier.predict(x_test)
print(y_pred)


[0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0
 0 0 1]


In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)


Confusion Matrix : 
 [[31  1]
 [ 1  7]]


In [13]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Accuracy :  0.95


In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.10, random_state=0)
def Std(input_data):
  mean0 = np.mean(input_data[:, 0])
  sd0 = np.std(input_data[:, 0])
  mean1 = np.mean(input_data[:, 1])
  sd1 = np.std(input_data[:, 1])
  return lambda x:((x[0]-mean0)/sd0, (x[1]-mean1)/sd1)
my_std = Std(x)
my_std(x_train[0])

(-1.017692393473028, 0.5361288690822568)

In [25]:
def standardize(X_tr):
  for i in range(shape(X_tr)[1]):
    X_tr[:,i] = (X_tr[:,i] - np.mean(X_tr[:,i]))/np.std(X_tr[:,i])
def F1_score(y,y_hat):
  tp,tn,fp,fn = 0,0,0,0
  for i in range(len(y)):
    if y[i] == 1 and y_hat[i] == 1:
      tp += 1
    elif y[i] == 1 and y_hat[i] == 0:
      fn += 1
    elif y[i] == 0 and y_hat[i] == 1:
      fp += 1
    elif y[i] == 0 and y_hat[i] == 0:
      tn += 1
      precision = tp/(tp+fp)
      recall = tp/(tp+fn)
      f1_score = 2*precision*recall/(precision+recall)
  return f1_score

In [26]:
def sigmoid(self,z):
  sig = 1/(1+exp(-z))
  return sig

In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

# Load data
data = pd.read_csv('suv_data.csv')

# Extract features and target variable
X = data.iloc[:, [2, 3]].values
y = data.iloc[:, 4].values

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features (using sklearn)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# In-built Logistic Regression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

# Evaluation metrics for in-built model
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("In-built Logistic Regression:")
print("Confusion Matrix:\n", cm)
print("Accuracy:", accuracy)
print("F1-score:", f1)

# User-defined Logistic Regression (improved)
class LogisticRegression:
    def __init__(self, learning_rate=0.01, num_iterations=1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def initialize_weights(self, X):
        self.weights = np.zeros((X.shape[1] + 1, 1))  # Add one for bias term
        self.X = np.hstack((np.ones((X.shape[0], 1)), X))  # Add bias term

    def fit(self, X, y):
        self.initialize_weights(X)
        y = y.reshape(-1, 1) # Reshape y to be a column vector

        for _ in range(self.num_iterations):
            z = np.dot(self.X, self.weights)
            h = self.sigmoid(z)
            gradient = np.dot(self.X.T, (h - y)) / len(y)
            self.weights -= self.learning_rate * gradient

    def predict(self, X):
        X = np.hstack((np.ones((X.shape[0], 1)), X))  # Add bias term for prediction
        z = np.dot(X, self.weights)
        predictions = np.round(self.sigmoid(z))
        return predictions

# Create and train user-defined Logistic Regression model
user_defined_model = LogisticRegression()
user_defined_model.fit(X_train, y_train)
y_pred_user_defined = user_defined_model.predict(X_test)

# Evaluation metrics for user-defined model
cm_user_defined = confusion_matrix(y_test, y_pred_user_defined)
accuracy_user_defined = accuracy_score(y_test, y_pred_user_defined)
f1_user_defined = f1_score(y_test, y_pred_user_defined)

print("\nUser-defined Logistic Regression:")
print("Confusion Matrix:\n", cm_user_defined)
print("Accuracy:", accuracy_user_defined)
print("F1-score:", f1_user_defined)


In-built Logistic Regression:
Confusion Matrix:
 [[50  2]
 [ 9 19]]
Accuracy: 0.8625
F1-score: 0.7755102040816326

User-defined Logistic Regression:
Confusion Matrix:
 [[50  2]
 [ 9 19]]
Accuracy: 0.8625
F1-score: 0.7755102040816326
