In [1]:
import pandas as pd
import numpy as np

In [2]:
bnotes = pd.read_csv('test.csv')
bnotes.head(10)

VWTI       SWTI       CWTI       EI
0 -0.40804   0.542140  -0.527250  0.65860
1 -3.71810  -8.508900  12.363000 -0.95518
2  5.50400  10.367100  -4.413000 -4.02110
3  1.68490   8.748900  -1.264100 -1.38580
4  4.74320   2.108600   0.136800  1.65430
5 -0.39416  -0.020702  -0.066267 -0.44699
6  0.48797   3.567400  -4.388200 -3.81160
7 -0.27802   8.188100  -3.133800 -2.52760
8 -0.30432   2.652800  -2.775600 -0.65647
9 -4.02180  -8.304000  12.555000 -1.50990

In [3]:
bnotes.describe(include= "all")

VWTI        SWTI        CWTI          EI
count  275.000000  275.000000  275.000000  275.000000
mean     0.363297    2.462609    1.030690   -1.330679
std      2.805872    5.624348    4.024623    2.165304
min     -7.042100  -13.497900   -5.215900   -7.871900
25%     -1.640650   -0.990160   -1.546900   -2.696950
50%      0.118060    2.752100    0.180500   -0.719840
75%      2.642950    7.019000    2.420700    0.368950
max      6.824800   12.951600   17.677200    1.928400

In [6]:
print(bnotes.columns)


Index(['VWTI', 'SWTI', 'CWTI', 'EI'], dtype='object')


In [12]:
bnotes.columns = bnotes.columns.str.strip()
print(bnotes.columns[bnotes.columns.duplicated()])
print(bnotes.head())


Index([], dtype='object')
      VWTI      SWTI      CWTI       EI
0 -0.40804   0.54214  -0.52725  0.65860
1 -3.71810  -8.50890  12.36300 -0.95518
2  5.50400  10.36710  -4.41300 -4.02110
3  1.68490   8.74890  -1.26410 -1.38580
4  4.74320   2.10860   0.13680  1.65430


In [20]:
print(bnotes.head())  # Print first few rows
print(bnotes.columns)  # Print column names


import pandas as pd

# Load your DataFrame (example)
bnotes = pd.read_csv('test.csv')  # Adjust the filename as needed

# Check the columns
print(bnotes.columns)

# Suppose you want to create a 'Class' column based on 'score'
if 'score' in bnotes.columns:
    bnotes['Class'] = (bnotes['score'] > some_threshold).astype(int)
else:
    print("Column 'score' does not exist.")


      VWTI      SWTI      CWTI       EI
0 -0.40804   0.54214  -0.52725  0.65860
1 -3.71810  -8.50890  12.36300 -0.95518
2  5.50400  10.36710  -4.41300 -4.02110
3  1.68490   8.74890  -1.26410 -1.38580
4  4.74320   2.10860   0.13680  1.65430
Index(['VWTI', 'SWTI', 'CWTI', 'EI'], dtype='object')
Index(['VWTI', 'SWTI', 'CWTI', 'EI'], dtype='object')
Column 'score' does not exist.


In [22]:
if 'Class' in bnotes.columns:
    from sklearn.model_selection import train_test_split
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

    from sklearn.neural_network import MLPClassifier
    mlp = MLPClassifier(max_iter=500, activation='relu')
    mlp.fit(x_train, y_train)


In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

# Load the dataset
data = pd.read_csv('test.csv')

# Define features (X) and target variable (y)
X = data.drop('EI', axis=1)  # Features
y = data['EI'].astype(int)    # Target variable (convert to integer if necessary)

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Create and train the MLP model
mlp = MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=1000, activation='relu', random_state=42)
mlp.fit(X_train, y_train)

# Make predictions
predictions = mlp.predict(X_test)

# Evaluate the model
conf_matrix = confusion_matrix(y_test, predictions)
class_report = classification_report(y_test, predictions, zero_division=0)

# Output results
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

# Additional output: Model configuration
print("Model Configuration:")
print(f"Activation Function: {mlp.activation}")
print(f"Hidden Layer Sizes: {mlp.hidden_layer_sizes}")
print(f"Max Iterations: {mlp.max_iter}")



Confusion Matrix:
[[ 0  1  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0]
 [ 0  1  1  0  0  0  0  0  0]
 [ 0  0  1  4  0  1  0  0  0]
 [ 0  0  2  1  0  2  0  0  0]
 [ 0  0  0  0  0  3  1  1  0]
 [ 0  0  0  0  0  1  4  6  0]
 [ 0  0  0  0  0  0  0 15  0]
 [ 0  0  0  0  0  0  0  9  0]]

Classification Report:
              precision    recall  f1-score   support

          -7       0.00      0.00      0.00         1
          -6       0.00      0.00      0.00         1
          -5       0.25      0.50      0.33         2
          -4       0.67      0.67      0.67         6
          -3       0.00      0.00      0.00         5
          -2       0.43      0.60      0.50         5
          -1       0.80      0.36      0.50        11
           0       0.48      1.00      0.65        15
           1       0.00      0.00      0.00         9

    accuracy                           0.49        55
   macro avg       0.29      0.35      0.29        55
weighted avg       0.41      0.49    

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# New Section